version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/task_manager:cached
      - ~/.ssh:/root/.ssh:ro
      - ~/.bash_history:/root/.bash_history:ro
      - bundle_cache:/bundle_cache
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      RAILS_ENV: development
    command: bundle exec rails server -b '0.0.0.0' -p 3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_development
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bundle_cache:
  db_data:
